name: Build, Run Tests and Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    container: node:latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: recipeorganizer
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install PostgreSQL client
      run: |
          apt-get update
          apt-get install --yes postgresql-client
          
    - name: Query database
      run: psql -h postgres -d recipeorganizer -U postgres -c 'SELECT 1;'
      env:
        PGPASSWORD: postgres

    - name: Create tables in PostgreSQL database
      run: psql -h postgres -d recipeorganizer -U postgres -f database.sql
      env:
        PGPASSWORD: postgres

    - name: Set Spring profile to "ci"
      run: echo "SPRING_PROFILES_ACTIVE=ci" >> $GITHUB_ENV

    - name: Clean up Gradle
      run: ./gradlew clean

    - name: Init Gradle
      run: ./gradlew init

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Analyze with SonarCloud
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew build sonar --info

    - name: Build Docker image and upload to Docker Hub
      if: ${{ success() && github.event_name == 'push' }}
      env:
          CURRENT_DEPLOYMENT: ${{ github.ref_name }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: ./gradlew jib

    - name: Deploy to Render
      if: ${{ success() && github.event_name == 'push' }}
      env:
          DEPLOY_URL_MAIN: ${{ secrets.RENDER_DEPLOY_HOOK_URL_MAIN }}
          DEPLOY_URL_DEVELOP: ${{ secrets.RENDER_DEPLOY_HOOK_URL_DEVELOP }}
      run: |
          if [ ${{ github.ref_name }} == 'main' ]; then
            echo "Deploy to Render recipeorganizer-ase-main"
            curl "$DEPLOY_URL_MAIN"
          else
            echo "Deploy to Render recipeorganizer-ase-develop"
            curl "$DEPLOY_URL_DEVELOP"
          fi
