name: Build, Run Tests and Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    container: node:latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: recipeorganizer
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Disabling shallow clones is recommended for improving the relevancy of reporting

    - name: Install PostgreSQL client
      run: |
          apt-get update
          apt-get install --yes postgresql-client
          
    - name: Query database
      run: psql -h postgres -d recipeorganizer -U postgres -c 'SELECT 1;'
      env:
        PGPASSWORD: postgres

    - name: Create tables in PostgreSQL database
      run: psql -h postgres -d recipeorganizer -U postgres -f database.sql
      env:
        PGPASSWORD: postgres

    - name: Set Spring profile to ci
      run: echo "SPRING_PROFILES_ACTIVE=ci" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false # Allow writing cache entries on non-default branches
        gradle-version: 8.2

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Analyze with SonarCloud
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonar --info

    - name: Build Docker image and upload to Docker Hub
      if: ${{ success() && github.event_name == 'push' }}
      env:
          CURRENT_DEPLOYMENT: ${{ github.ref_name }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: ./gradlew jib

    - name: Deploy to Render
      if: ${{ success() && github.event_name == 'push' }}
      env:
          DEPLOY_URL_MAIN: ${{ secrets.RENDER_DEPLOY_HOOK_URL_MAIN }}
          DEPLOY_URL_DEVELOP: ${{ secrets.RENDER_DEPLOY_HOOK_URL_DEVELOP }}
      run: |
          if ${{ (github.ref_name == 'main') }} == 'true'; then
            echo "Deploy to Render recipeorganizer-ase-main"
            curl "$DEPLOY_URL_MAIN"
          else
            echo "Deploy to Render recipeorganizer-ase-develop"
            curl "$DEPLOY_URL_DEVELOP"
          fi
